version: "1.0"
name: "skillgate-default"
description: "SkillGate default security policy for Claude Code skills"

# Score thresholds
thresholds:
  block: 40    # Score <= 40 -> block
  warn: 70     # Score <= 70 -> quarantine

# Rules that trigger immediate block regardless of score
critical_block:
  - secret_aws_access_key
  - secret_aws_secret_key
  - secret_private_key
  - secret_github_token
  - secret_openai_key
  - secret_anthropic_key
  - skill_rm_rf_root
  - skill_curl_bash
  - skill_wget_bash
  - skill_mkfs_command
  - entrypoint_curl_pipe_bash
  - entrypoint_wget_pipe_bash
  - static_ssh_access
  - static_aws_credentials
  - ci_secret_exposure

# Rule definitions
rules:
  # ===== Secret Scanner Rules =====
  secret_aws_access_key:
    severity: critical
    weight: -50
    message: "AWS Access Key ID detected"

  secret_aws_secret_key:
    severity: critical
    weight: -50
    message: "AWS Secret Access Key detected"

  secret_github_token:
    severity: critical
    weight: -50
    message: "GitHub token detected"

  secret_openai_key:
    severity: critical
    weight: -50
    message: "OpenAI API key detected"

  secret_anthropic_key:
    severity: critical
    weight: -50
    message: "Anthropic API key detected"

  secret_private_key:
    severity: critical
    weight: -50
    message: "Private key detected"

  secret_password_in_url:
    severity: high
    weight: -20
    message: "Password embedded in URL"

  secret_generic_api_key:
    severity: high
    weight: -15
    message: "Generic API key pattern detected"

  secret_jwt_token:
    severity: high
    weight: -15
    message: "JWT token detected"

  # ===== Skill Scanner Rules =====
  skill_rm_rf_root:
    severity: critical
    weight: -50
    message: "Destructive rm -rf targeting root or home"

  skill_rm_rf_generic:
    severity: high
    weight: -20
    message: "Recursive force delete command"

  skill_sudo_usage:
    severity: high
    weight: -15
    message: "sudo usage - elevated privileges required"

  skill_chmod_777:
    severity: high
    weight: -15
    message: "chmod 777 - insecure permissions"

  skill_curl_bash:
    severity: critical
    weight: -50
    message: "curl | bash - remote code execution"

  skill_wget_bash:
    severity: critical
    weight: -50
    message: "wget | bash - remote code execution"

  skill_bash_c:
    severity: medium
    weight: -10
    message: "Shell -c execution"

  skill_dd_command:
    severity: high
    weight: -20
    message: "dd command - can overwrite disk"

  skill_mkfs_command:
    severity: critical
    weight: -50
    message: "mkfs - filesystem format"

  skill_suspicious_download:
    severity: medium
    weight: -10
    message: "Download from non-standard source"

  skill_short_url:
    severity: high
    weight: -15
    message: "Shortened URL - unknown destination"

  skill_ip_address_url:
    severity: high
    weight: -15
    message: "Direct IP address URL"

  skill_env_var_access:
    severity: high
    weight: -15
    message: "Sensitive environment variable access"

  skill_sensitive_path_access:
    severity: high
    weight: -20
    message: "Sensitive system path access"

  # ===== Static Analyzer Rules =====
  static_eval_usage:
    severity: high
    weight: -15
    message: "eval() usage - code injection risk"

  static_exec_usage:
    severity: high
    weight: -15
    message: "exec() usage - command execution"

  static_child_process:
    severity: medium
    weight: -10
    message: "child_process module usage"

  static_spawn_exec:
    severity: medium
    weight: -10
    message: "Process spawn/exec"

  static_base64_decode:
    severity: medium
    weight: -10
    message: "Base64 decoding - potential obfuscation"

  static_char_code_obfuscation:
    severity: high
    weight: -20
    message: "Character code obfuscation"

  static_ssh_access:
    severity: critical
    weight: -30
    message: "SSH credential access pattern"

  static_aws_credentials:
    severity: critical
    weight: -30
    message: "AWS credential access pattern"

  static_env_file_access:
    severity: high
    weight: -15
    message: ".env file access"

  static_keychain_access:
    severity: high
    weight: -20
    message: "System keychain access"

  # ===== Entrypoint Detector Rules =====
  entrypoint_npm_postinstall:
    severity: high
    weight: -15
    message: "npm postinstall script"

  entrypoint_npm_preinstall:
    severity: high
    weight: -15
    message: "npm preinstall script"

  entrypoint_python_cmdclass:
    severity: high
    weight: -15
    message: "Python custom install commands"

  entrypoint_curl_pipe_bash:
    severity: critical
    weight: -50
    message: "curl | bash remote execution"

  entrypoint_wget_pipe_bash:
    severity: critical
    weight: -50
    message: "wget | bash remote execution"

  entrypoint_install_script:
    severity: high
    weight: -10
    message: "Installation shell script"

  # ===== Dependency Scanner Rules =====
  dependency_no_lockfile:
    severity: medium
    weight: -5
    message: "No lock file - non-deterministic dependencies"

  dependency_vuln_critical:
    severity: critical
    weight: -30
    message: "Critical vulnerability in dependency"

  dependency_vuln_high:
    severity: high
    weight: -20
    message: "High severity vulnerability in dependency"

  dependency_vuln_medium:
    severity: medium
    weight: -10
    message: "Medium severity vulnerability in dependency"

  # ===== CI Risk Analyzer Rules =====
  ci_write_all_permissions:
    severity: high
    weight: -15
    message: "CI workflow with write-all permissions"

  ci_secret_exposure:
    severity: critical
    weight: -40
    message: "Potential secret exposure in CI"

  ci_remote_script_execution:
    severity: high
    weight: -15
    message: "Remote script execution in CI"

  ci_unpinned_action:
    severity: medium
    weight: -5
    message: "Unpinned GitHub Action"

  ci_third_party_action:
    severity: medium
    weight: -5
    message: "Third-party action without SHA pin"

  ci_pull_request_target:
    severity: high
    weight: -15
    message: "pull_request_target usage - injection risk"

# Default exceptions (can be overridden)
exceptions:
  - pattern: "test/**"
    ignore:
      - secret_generic_api_key
      - secret_jwt_token
    reason: "Test fixtures may contain mock secrets"

  - pattern: "**/*.test.{js,ts}"
    ignore:
      - static_eval_usage
    reason: "Tests may use eval for testing purposes"

  - pattern: "**/examples/**"
    ignore:
      - skill_curl_bash
      - skill_wget_bash
    reason: "Examples may demonstrate dangerous patterns"
